pipeline:
  build:
    image: node:9
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
  release:
    image: plugins/npm
    username: flowup
    email: hello@flowup.cz
    password: $PASSWORD
    secrets: [password]
