pipeline:
  build:
    image: node:9
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
  release:
    when:
        event: tag
    image: plugins/npm
    username: flowup
    password: $PASSWORD
    secrets: [password]
