swagger: '2.0'
info:
  description: |
    API doc
  version: "1.0.0"
  title: Esquare
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /report/ministry/issues:
    get:
      tags:
      - Data Import (Ministry)
      summary: Get issues list
      description: |
        [Screenshot from design](http://prntscr.com/i40s18)
      operationId: getIssuesList
      parameters:
      - $ref: '#/parameters/Period'
      - $ref: '#/parameters/IssueStatus'
      - name: pageSize
        in: query
        required: true
        type: integer
        format: int32
      - name: page
        in: query
        description: page number
        required: true
        type: integer
        format: int32
      - name: orderBy
        in: query
        enum:
          - name
          - school
          - dueDate
          - alert
        description: name | school | dueDate | alert
        required: true
        type: string
      - $ref: '#/parameters/Order'
      produces:
      - application/json
      - application/xml
      security:
        - JWT: []
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              total:
                type: integer
              list:
                type: array
                items:
                  $ref: '#/definitions/Issue'
        400:
          description: Invalid status value
        401:
          description: Unauthorized access

parameters:
  Period:
    name: period
    in: query
    type: integer
    enum:
      - 1 #Year
      - 2 #Month
      - 3 #Week
    description: |
      - 1 Year
      - 2 Month
      - 3 Week
  Order:
    name: order
    in: query
    type: string
    enum:
      - asc #asc
      - desc #desc
    description: |
      - asc
      - desc
  IssueStatus:
    name: status
    in: query
    type: integer
    enum:
      - 1 #Pending
      - 2 #Resolved
    description: |
      - 1 Pending
      - 2 Resolved

definitions:
  Issue:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      school:
        type: string
      dueDate:
        type: string
        format: data-time
      alert:
        $ref: '#/definitions/IssueAlertType'
      reportName:
        type: string
      description:
        type: string
      rootCause:
        type: string
  IssueAlertType:
    type: integer
    enum:
      - 1 #Validation error
      - 2 #Data override
    description: |
      - 1 Validation error
      - 2 Data override